const res = [
  {id: 0, title: 'MBA Inovação e Gestão Ágil', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Intermediário', macroArea: 'Agile'},
  {id: 1, title: 'MBA Gestão Ágil de Projetos', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 2, title: 'MBA Gestão de Processos de Negócio', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Agile',
  tags: ['BPM',
  'Modelagem de processos de negócios (BPMN)',
  'Estratégia organizacional',
  'BizAgi',
  'Gestor de Processos',
  'Analista de Processos']},
  {id: 3, title: 'MBA Gestão Ágil de Produtos', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 4, title: 'MBA Engenharia de Software Ágil', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Agile',
  tags: ['Software Engineer',
  'Manifesto Ágil',
  'DevOps',
  'Pipelines',
  'Telemetria',
  'Ciclos de Vida de Desenvolvimento de Software - CVDS']},
  {id: 5, title: 'MBA Segurança Cibernética', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Cibersegurança',
  tags: ['Cibersegurança',
  'Hacker',
  'Proteção',
  'Red Team',
  'Blue Team',
  'Ransonware']},
  {id: 6, title: 'MBA Cloud Computing', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Cloud Computing',
  tags: ['Computação em Nuvem',
  'Plataforma como Serviço - PaaS',
  'Infraestrutura como Serviço - IaaS',
  'Software como Serviço - SaaS',
  'Cloud Adoption Framework',
  'Microsoft Azure',
  'Amazon Web Services - AWS']},
  {id: 7, title: 'MBA Business Intelligence', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Data Science',
  tags: ['Tomada de decisão',
  'Organizações orientadas a dados (Data Driven)',
  'Desenvolvedor BI',
  'Gestor de BI',
  'Análise de dados',
  'Power BI']},
  {id: 8, title: 'MBA Data Analytics', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Data Science',
  tags: ['Visualização de Dados',
  'Governança de Dados',
  'Data Literacy',
  'Power BI',
  'Data Storytelling',
  'Data Mesh']},
  {id: 9, title: 'MBA Cientista de Dados', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Avançado', macroArea: 'Data Science'},
  {id: 10, title: 'MBA Engenharia de Dados', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Data Science',
  tags: ['Big Data',
  'SQL',
  'Python',
  'AWS',
  'Real Time Analytics',
  'Kubernetes']},
  {id: 11, title: 'MBA Arquitetura de Software e Soluções', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Avançado', macroArea: 'Development',
  tags: ['Arquiteto de Software',
  'Arquiteto de Solução',
  'Computação em Nuvem',
  'Cybersecurity',
  'Banco de Dados',
  'Soluções Digitais']},
  {id: 12, title: 'MBA Desenvolvimento Front End', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Development',
  tags: ['Angular',
  'Vue',
  'HTML',
  'CSS',
  'JavaScript',
  'Acessibilidade',
  'Desenvolvimento',
  'Web',
  'Programador',
  'Desenvolvedor']},
  {id: 13, title: 'MBA Desenvolvimento Full Stack', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Avançado', macroArea: 'Development'},
  {id: 14, title: 'MBA Desenvolvimento Mobile', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Development'},
  {id: 15, title: 'MBA DevOps e SRE', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 16, title: 'MBA Experiência & Sucesso do Cliente', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Experiência do Cliente'},
  {id: 17, title: 'MBA Ciência de Dados para o Mercado Financeiro', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Finanças'},
  {id: 18, title: 'MBA Gestão Exponencial', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Finanças'},
  {id: 19, title: 'MBA Ações e Stock Picking', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Finanças'},
  {id: 20, title: 'MBA Investimentos e Private Banking', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Intermediário', macroArea: 'Finanças'},
  {id: 21, title: 'MBA Gestão de TI', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Gestão de TI'},
  {id: 22, title: 'MBA Machine Learning', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Inteligência Artificial'},
  {id: 23, title: 'MBA Inovação e Transformação Digital', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 24, title: 'Bootcamp Programador de software iniciante', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Java',
  'Lógica de Programação',
  'Python',
  'Front-end',
  'Orientação a objetos',
  'JavaScript']},
  {id: 25, title: 'Bootcamp Agile Expert', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 26, title: 'Bootcamp Analista de Processos de Negócios', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile',
  tags: ['BPM',
  'Estratégia organizacional',
  'Modelagem de processos de negócios (BPMN)',
  'BPMS (suítes BPM)',
  'BizAgi',
  'Simulação de processos',
  'Automatização de processos']},
  {id: 27, title: 'Bootcamp Engenheiro(a)de Software Ágil', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile',
  tags: ['Software Engineer',
  'SCRUM',
  'Integração Contínua - CI',
  'Entrega Contínua - CD',
  'Qualidade de Software',
  'TDD (Test Driven Development)']},
  {id: 28, title: 'Bootcamp Gerente de Projetos', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 29, title: 'Bootcamp Gestor(a) de Processos de Negócios', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile',
  tags: ['BPM',
  'Gestor de Processos',
  'Estratégia organizacional',
  'Melhoria de processos de negócios',
  'Gestão do conhecimento',
  'Gestão ágil de projetos']},
  {id: 30, title: 'Bootcamp Product Manager', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 31, title: 'Bootcamp Product Owner', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 32, title: 'Bootcamp Profissional Devops', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 33, title: 'Bootcamp Profissional SRE', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cibersegurança'},
  {id: 34, title: 'Bootcamp Analista de Ataque Cibernético', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cibersegurança'},
  {id: 35, title: 'Bootcamp Analista de Defesa Cibernética', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cloud Computing'},
  {id: 36, title: 'Bootcamp Arquiteto(a) Cloud Computing', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cloud Computing',
  tags: ['Computação em Nuvem',
  'Arquiteto de Solução em Nuvem',
  'Plataforma como Serviço - PaaS',
  'Infraestrutura como Serviço - IaaS',
  'Software como Serviço - SaaS',
  'Nuvem pública']},
  {id: 37, title: 'Bootcamp Profissional AWS Cloud Computing', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cloud Computing',
  tags: ['AWS',
  'RDS',
  'Well Architected Framework - WAF',
  'EC2',
  'S3',
  'Certificação AWS Cloud Practitioner']},
  {id: 38, title: 'Bootcamp Profissional Azure Cloud Computing', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Azure DevOps',
  'Azure SQL Database',
  'Azure Data Factory',
  'Azure Functions',
  'Azure IoT Hub',
  'Cloud Adoption Framework',
  'Certificação AZ900 - Azure Fundamentals']},
  {id: 39, title: 'Bootcamp Analista de Banco de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Modelagem de Dados',
  'Banco de Dados',
  'Linguagem SQL',
  'SGBD',
  'SQL Server',
  'MongoDB',]},
  {id: 40, title: 'Bootcamp Analista de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Visualização de Dados',
  'KPIs',
  'Data Mining',
  'Power BI',
  'Data Storytelling',
  'Business Intelligence']},
  {id: 41, title: 'Bootcamp Arquiteto(a) de Big Data', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Big Data',
  'Hadoop',
  'Spark',
  'Web scraping',
  'Data lake',
  'Data warehouse']},
  {id: 42, title: 'Bootcamp Cientista de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Teste AB',
  'Machine Learning',
  'Storytelling',
  'Power BI',
  'Inteligência Artificial']},
  {id: 43, title: 'Bootcamp Cientista de Dados de Renda Fixa', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 44, title: 'Bootcamp Cientista de Dados de Renda Variável', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 45, title: 'Bootcamp Desenvolvedor(a) Business Intelligence', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Desenvolvedor BI',
  'Data Warehouse',
  'Ferramentas de BI',
  'Dashboards',
  'ETL',
  'Power BI',]},
  {id: 46, title: 'Bootcamp Engenheiro(a) de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Engenharia de Dados',
  'Big Data',
  'Data Pipelines',
  'ETL',
  'SQL',
  'Python']},
  {id: 47, title: 'Bootcamp Engenheiro(a) de Dados Cloud', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Big Data',
  'AWS',
  'Azure',
  'Google Cloud',
  'Real Time Analytics',
  'Kubernetes']},
  {id: 48, title: 'Bootcamp Gestor(a) de Business Intelligence', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Gestor de BI',
  'Estratégia organizacional',
  'Gestão da informação e do conhecimento',
  'Mineração de dados',
  'Análise de dados',
  'Tomada de decisão']},
  {id: 49, title: 'Bootcamp Gestor(a) de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Visualização de Dados',
  'Governança de Dados',
  'Data Literacy',
  'Data Mesh',
  'Data Lake',
  'Self service BI']},
  {id: 50, title: 'Bootcamp Administrador(a) Linux', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['OpenSource',
  'Linux',
  'Comunidade',
  'GNU',
  'Liberdade',
  'Certificação']},
  {id: 51, title: 'Bootcamp Arquiteto(a) de Software', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Arquiteto de Software',
  'Design Patterns',
  'Estilos Arquiteturais',
  'C4 Model',
  'Enterprise Application Architecture Patterns',
  'Framework Arquitetural TOGAF']},
  {id: 52, title: 'Bootcamp Arquiteto(a) de Soluções', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Arquiteto de Solução',
  'Computação em Nuvem',
  'Cybersecurity',
  'Plataforma de Dados',
  'Internet of Things - IoT',
  'Soluções Cloud First']},
  {id: 53, title: 'Bootcamp Desenvoldedor(a) Python', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['PyGame',
  'Flask',
  'Django',
  'Automação de Processos',
  'Machine Learning',
  'Ciência de Dados']},
  {id: 54, title: 'Bootcamp Desenvolvedor(a) Front-End', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Angular',
  'Vue',
  'HTML',
  'CSS',
  'JavaScript',
  'Acessibilidade',
  'Desenvolvimento',
  'Web',
  'Programador',
  'Desenvolvedor']},
  {id: 55, title: 'Bootcamp Desenvolvedor(a) Mobile Multiplataforma', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Mobile',
  'React',
  'React Native',
  'Flutter',
  'Arquitetura',
  'Desenvolvimento',
  'Programador',
  'Desenvolvedor']},
  {id: 56, title: 'Bootcamp Desenvolvedor Mobile Android', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Mobile',
  'Android',
  'Java',
  'Kotlin',
  'Arquitetura',
  'Desenvolvimento']},
  {id: 57, title: 'Bootcamp Desenvolvedor(a) Node js', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development',
  tags: ['Node',
  'SQL',
  'NOSQL',
  'Autenticação',
  'Autorização',
  'Bancos de Dados',
  'Desenvolvimento',
  'Programador',
  'Desenvolvedor']},
  {id: 58, title: 'Bootcamp Desenvolvedor(a) React', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital',
  tags: ['React',
  'Hooks',
  'Next',
  'Jest',
  'Testes',
  'JavaScript',
  'Desenvolvimento', 
  'Web',
  'Programador',
  'Desenvolvedor']},
  {id: 59, title: 'Bootcamp Gestor(a) de Operações de TI', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 60, title: 'Bootcamp Gestor(a) de TI', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 61, title: 'Bootcamp Arquiteto(a) de Machine Learning', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital',
  tags: ['IoT (internet das Coisas)',
  'PLN (processamento da linguagem natural)',
  'Sistemas de Recomendação',
  'Healthcare',
  'Smart Farming',
  'Visão Computacional']},
  {id: 62, title: 'Bootcamp Engenheiro(a) de Machine Learning', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital',
  tags: ['Inteligência Artificial',
  'Python',
  'Séries temporais',
  'Deep Learning',
  'Regressão',
  'Classificação']},
  {id: 63, title: 'Bootcamp Analista de Inovação', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital',},
  {id: 64, title: 'Bootcamp Analista de Transformação Digital', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 65, title: 'Bootcamp Analista de Marketing Digital', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 66, title: 'Bootcamp Experiência do Cliente', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 67, title: 'Bootcamp Sucesso do Cliente', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 68, title: 'Graduação Ciência de Dados', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Big Data',
  'Python',
  'Machine Learning',
  'Apache Spark',
  'Deep Learning',
  'Data Storytelling ']},
  {id: 69, title: 'Graduação Sistemas de Informação', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 70, title: 'Graduação Tecnologia em Análise e Desenvolvimento de Sistemas', courseType: 'Graduação',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 71, title: 'Graduação Tecnologia em Banco de Dados', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Data Science',
  tags: ['Modelagem de Dados',
  'Banco de Dados',
  'Arquiteto de Dados',
  'Linguagem SQL',
  'SGBD',
  'SQL Server',
  'MongoDB']},
  {id: 72, title: 'Graduação Tecnologia em Defesa Cibernética', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Cibersegurança',
  tags: ['Proteção',
  'Cibersegurança',
  'Risco',
  'Hacker',
  'SOC',
  'Privacidade']},
  {id: 73, title: 'Imersão Internacional Agile World', courseType: 'Imersão Internacional',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 74, title: 'Imersão Internacional AI Solutions', courseType: 'Imersão Internacional',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Inteligência Artificial',
  tags: ['Visão Computacional',
  'Healthcare',
  'Inteligência Artificial',
  'Deep Learning']},
  {id: 75, title: 'Imersão Internacional Vale do Silício Tecnologias Disruptivas', courseType: 'Imersão Internacional',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 76, title: 'Imersão Internacional Desafio da prosperidade para casais', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira'},
  {id: 77, title: 'Cursos Rápidos Educação Financeira para Jovens', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira',
  tags: ['Finanças',
  'Educação Financeira',
  'Planejamento Financeiro',
  'Poupar Dinheiro',
  'Independência Financeira',
  'Educação Financeira para Jovens']},
  {id: 78, title: 'Cursos Rápidos O Beabá Financeiro', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira',
  tags: ['Finanças',
  'Educação Financeira',
  'Planejamento Financeiro',
  'Metas Financeiras',
  'Quitar Dívidas',
  'Poupar Dinheiro',
  'Juros',
  'Inflação',
  'Taxa Selic',
  'Investimento para Iniciante']},
  {id: 79, title: 'Cursos Rápidos O Poder do Autoconhecimento Financeiro', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira',
  tags: ['Finanças',
  'Educação Financeira',
  'Planejamento Financeiro',
  'Metas Financeiras',
  'Autoconhecimento Financeiro']},
  {id: 80, title: 'Cursos Rápidos Cursos Rápidos Dinheiro Sem Tabu: Crenças Limitantes', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira', 
  tags: ['Finanças',
  'Educação Financeira',
  'Planejamento Financeiro',
  'Metas Financeiras',
  'Crenças Limitantes Sobre Dinheiro']},
  {id: 81, title: 'Cursos Rápidos Criptoinvestidor', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos',
  tags: ['Criptomoedas',
  'Criptoativos',
  'Moedas Virtuais',
  'Bitcoin',
  'Criptomoedas para iniciantes',
  'Carteira de Investimentos']},
  {id: 82, title: 'Cursos Rápidos Especialista em Investimentos no Exterior: Encontre Oportunidades Fora do Brasil', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos',
  tags: ['Renda Variável',
  'Renda Fixa',
  'Investimentos no exterior',
  'Investimentos nos EUA',
  'Mercado de Bonds',
  'Dólar',
  'Carteira de Investimentos']},
  {id: 83, title: 'Cursos Rápidos In the Money: Como começar a lucrar com opções', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos',
  tags: ['Renda Variável',
  'Dólar',
  'Carteira de Investimentos',
  'Mercado de Opções',
  'Mercado de Derivativos']},
  {id: 84, title: 'Cursos Rápidos Previdência e Planejamento: Turbinando a sua Aposentadoria', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos',
  tags: ['Previdência Privada',
  'Fundos de Previdência Privada',
  'Carteira de Investimentos',
  'Metas Financeiras']},
  {id: 85, title: 'Cursos Rápidos Renda fixa: Ganhos com Baixo Risco', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos', 
  tags: ['Renda Fixa',
  'Carteira de Investimentos',
  'Carteira de Investimentos',
  'Inflação',
  'Juros',
  'Taxa Selic']},
  {id: 86, title: 'Cursos Rápidos Consistência no Day Trade & Gestão Emocional', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Trading',
  tags: ['Renda Variável',
  'Juros',
  'Inflação',
  'Gráficos',
  'Rentabilidade de Ações',
  'Trading',
  'Day Trade',
  'Day Trade para Iniciantes']},
  {id: 87, title: 'Cursos Rápidos Introdução ao Universo de Trading: conceitos básicos', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Trading',
  tags: ['Renda Variável',
  'Gráfico',
  'Rentabilidade de Ações',
  'Trading',
  'Day Trade',
  'Day Trade para Iniciantes',
  'Swing Trade',
  'Swing Trade para Iniciante']},
  {id: 88, title: 'Cursos Rápidos Minicontratos do zero: conceitos e operacionais', courseType: 'Cursos Rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Trading',
  tags: ['Renda Fixa',
  'Carteira de Investimentos',
  'Inflação',
  'Juros',
  'Taxa Selic']},
]

/// utilizando string para simular o retorno de uma API

const api = {
    async get(){
        return Promise.resolve(JSON.stringify(res))
    }
}