const res = [
  {id: 0, title: 'MBA em Inovação e Gestão Ágil', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Intermediário', macroArea: 'Agile'},
  {id: 1, title: 'MBA em Gestão Ágil de Projetos', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 2, title: 'MBA em Gestão de Processos de Negócio', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Agile'},
  {id: 3, title: 'MBA em Gestão Ágil de Produtos', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 4, title: 'MBA em Engenharia de Software Ágil', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Agile'},
  {id: 5, title: 'MBA em Segurança Cibernética', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Cibersegurança'},
  {id: 6, title: 'MBA em Cloud Computing', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Cloud Computing'},
  {id: 7, title: 'MBA em Business Intelligence', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Data Science'},
  {id: 8, title: 'MBA em Data Analytics', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Data Science'},
  {id: 9, title: 'MBA em Cientista de Dados', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Avançado', macroArea: 'Data Science'},
  {id: 10, title: 'MBA em Engenharia de Dados', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Data Science'},
  {id: 11, title: 'MBA em Arquitetura de Software e Soluções', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Avançado', macroArea: 'Development'},
  {id: 12, title: 'MBA em Desenvolvimento Front End', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Iniciante', macroArea: 'Development'},
  {id: 13, title: 'MBA em Desenvolvimento Full Stack', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Avançado', macroArea: 'Development'},
  {id: 14, title: 'MBA em Desenvolvimento Mobile', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Development'},
  {id: 15, title: 'MBA em DevOps e SRE', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 16, title: 'MBA em Experiência & Sucesso do Cliente', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Experiência do Cliente'},
  {id: 17, title: 'MBA em Ciência de Dados para o Mercado Financeiro', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Finanças'},
  {id: 18, title: 'MBA em Gestão Exponencial', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel:'Intermediário', macroArea: 'Finanças'},
  {id: 19, title: 'MBA em Ações e Stock Picking', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Finanças'},
  {id: 20, title: 'MBA em Investimentos e Private Banking', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Intermediário', macroArea: 'Finanças'},
  {id: 21, title: 'MBA em Gestão de TI', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Gestão de TI'},
  {id: 22, title: 'MBA em Machine Learning', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Avançado', macroArea: 'Inteligência Artificial'},
  {id: 23, title: 'MBA em Inovação e Transformação Digital', courseType: 'MBA',schoolarshipLevel: 'Graduação completa', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 24, title: 'Programador de software iniciante', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Iniciante'},
  {id: 25, title: 'Agile Expert', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 26, title: 'Analista de Processos de Negócios', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 27, title: 'Engenheiro(a)de Software Ágil', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 28, title: 'Gerente de Projetos', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 29, title: 'Gestor(a) de Processos de Negócios', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 30, title: 'Product Manager', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 31, title: 'Product Owner', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 32, title: 'Profissional Devops', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 33, title: 'Profissional SRE', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cibersegurança'},
  {id: 34, title: 'Analista de Ataque Cibernético', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cibersegurança'},
  {id: 35, title: 'Analista de Defesa Cibernética', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cloud Computing'},
  {id: 36, title: 'Arquiteto(a) Cloud Computing', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cloud Computing'},
  {id: 37, title: 'Profissional AWS Cloud Computing', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Cloud Computing'},
  {id: 38, title: 'Profissional Azure Cloud Computing', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 39, title: 'Analista de Banco de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 40, title: 'Analista de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 41, title: 'Arquiteto(a) de Big Data', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 42, title: 'Cientista de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 43, title: 'Cientista de Dados de Renda Fixa', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 44, title: 'Cientista de Dados de Renda Variável', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 45, title: 'Desenvolvedor(a) Business Intelligence', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 46, title: 'Engenheiro(a) de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 47, title: 'Engenheiro(a) de Dados Cloud', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 48, title: 'Gestor(a) de Business Intelligence', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 49, title: 'Gestor(a) de Dados', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 50, title: 'Administrador(a) Linux', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 51, title: 'Arquiteto(a) de Software', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 52, title: 'Arquiteto(a) de Soluções', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 53, title: 'Desenvoldedor(a) Python', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 54, title: 'Desenvolvedor(a) Front-End', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 55, title: 'Desenvolvedor(a) Mobile Multiplataforma', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 56, title: 'Desenvolvedor Mobile Android', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 57, title: 'Desenvolvedor(a) Node js', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 58, title: 'Desenvolvedor(a) React', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 59, title: 'Gestor(a) de Operações de TI', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 60, title: 'Gestor(a) de TI', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 61, title: 'Arquiteto(a) de Machine Learning', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 62, title: 'Engenheiro(a) de Machine Learning', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 63, title: 'Analista de Inovação', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 64, title: 'Analista de Transformação Digital', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 65, title: 'Analista de Marketing Digital', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 66, title: 'Experiência do Cliente', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 67, title: 'Sucesso do Cliente', courseType: 'Bootcamp',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 68, title: 'Ciência de Dados', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 69, title: 'Sistemas de Informação', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 70, title: 'Tecnologia em Análise e Desenvolvimento de Sistemas', courseType: 'Graduação',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Development'},
  {id: 71, title: 'Tecnologia em Banco de Dados', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Data Science'},
  {id: 72, title: 'Tecnologia em Defesa Cibernética', courseType: 'Graduação',schoolarshipLevel: 'Ensino médio completo', difficultyLevel: 'Iniciante', macroArea: 'Cibersegurança'},
  {id: 73, title: 'Agile World', courseType: 'Imersão Internacional',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Agile'},
  {id: 74, title: 'AI Solutions', courseType: 'Imersão Internacional',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Inteligência Artificial'},
  {id: 75, title: 'Vale do Silício Tecnologias Disruptivas', courseType: 'Imersão Internacional',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Transformação Digital'},
  {id: 76, title: 'Desafio da prosperidade para casais', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira'},
  {id: 77, title: 'Educação Financeira para Jovens', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira'},
  {id: 78, title: 'O Beabá Financeiro', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira'},
  {id: 79, title: 'O Poder do Autoconhecimento Financeiro', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira'},
  {id: 80, title: 'Dinheiro Sem Tabu: Crenças Limitantes', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Educação Financeira'},
  {id: 81, title: 'Criptoinvestidor', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos'},
  {id: 82, title: 'Especialista em Investimentos no Exterior: Encontre Oportunidades Fora do Brasil', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos'},
  {id: 83, title: 'In the Money: Como começar a lucrar com opções', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos'},
  {id: 84, title: 'Previdência e Planejamento: Turbinando a sua Aposentadoria', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos'},
  {id: 85, title: 'Renda fixa: Ganhos com Baixo Risco', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Investimentos'},
  {id: 86, title: 'Consistência no Day Trade & Gestão Emocional', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Trading'},
  {id: 87, title: 'Introdução ao Universo de Trading: conceitos básicos', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Trading'},
  {id: 88, title: 'Minicontratos do zero: conceitos e operacionais', courseType: 'Cursos rápidos',schoolarshipLevel: 'Livre', difficultyLevel: 'Iniciante', macroArea: 'Trading'},
]

/// utilizando string para simular o retorno de uma API

const api = {
    async get(){
        return Promise.resolve(JSON.stringify(res))
    }
}